version: '3'

services:

  redis:
    image: redis
    restart: always
    hostname: redis

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

     
  web:
    build: 
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=pgdb
      - DB_USER=user
      - DB_PASSWORD=password
    command: python manage.py runserver 0.0.0.0:8000
    
    depends_on:
      - db
  
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A projects_website.celery_app worker --loglevel=info
    volumes:
      - ./services:/services
    environment:
      - DB_HOST=db
      - DB_NAME=pgdb
      - DB_USER=user
      - DB_PASSWORD=password
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
  
  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A projects_website.celery_app flower
    volumes:
      - ./services:/services
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    ports:
      - "5555:5555"
    


volumes:
  pgdbdata: null


