# Generated by Django 5.0 on 2024-02-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_initial'),
        ('showcase_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place', models.IntegerField(default=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='registration.profile')),
                ('lecturer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='registration.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MotivationLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to='letters/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.project')),
            ],
        ),
    ]
