# Generated by Django 5.0 on 2024-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('processing', 'В обработке'), ('rejected', 'Отклонен')], default='processing', max_length=20),
        ),
    ]
