# Generated by Django 5.0 on 2024-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_initial'),
        ('showcase_projects', '0003_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='participated_projects', to='registration.profile'),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
