# Generated by Django 5.0 on 2024-02-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0005_customer_lecturer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.student'),
        ),
    ]
