# Generated by Django 5.0 on 2024-03-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0005_remove_project_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationletters',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('processing', 'В обработке'), ('rejected', 'Отклонен')], default='processing', max_length=20),
        ),
    ]
