# Generated by Django 5.0 on 2024-03-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0006_motivationletters_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivationletters',
            options={'permissions': [('download_motivation_letters', 'Can download motivation letters')]},
        ),
    ]
