# Generated by Django 5.0 on 2024-03-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0007_alter_motivationletters_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivationletters',
            options={'permissions': [('download_motivation_letters', 'Can download motivation letters'), ('change_status_motivation_letters', 'Can change status motivation letters')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('change_status_project', 'Can change status project')]},
        ),
    ]
