# Generated by Django 5.0 on 2024-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0008_alter_motivationletters_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivationletters',
            options={'permissions': [('download_motivationletters', 'Can download motivation letters'), ('change_status_motivationletters', 'Can change status motivation letters')]},
        ),
    ]
