# Generated by Django 5.0 on 2024-02-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0011_timerestrictions_alter_project_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMotivationLetters',
            fields=[
                ('timerestrictions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='showcase_projects.timerestrictions')),
            ],
            options={
                'abstract': False,
            },
            bases=('showcase_projects.timerestrictions',),
        ),
        migrations.CreateModel(
            name='TimeParticipation',
            fields=[
                ('timerestrictions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='showcase_projects.timerestrictions')),
            ],
            options={
                'abstract': False,
            },
            bases=('showcase_projects.timerestrictions',),
        ),
        migrations.RemoveField(
            model_name='motivationletters',
            name='timeRestrictions',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='timeRestrictions',
        ),
        migrations.AddField(
            model_name='motivationletters',
            name='time',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.timemotivationletters'),
        ),
        migrations.AddField(
            model_name='participation',
            name='time',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.timeparticipation'),
        ),
    ]
