# Generated by Django 5.0 on 2024-02-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0012_timemotivationletters_timeparticipation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationletters',
            name='time',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='time',
        ),
    ]
