# Generated by Django 5.0 on 2024-02-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0013_remove_motivationletters_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationletters',
            name='time',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.timemotivationletters'),
        ),
        migrations.AddField(
            model_name='participation',
            name='time',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.timeparticipation'),
        ),
    ]
