# Generated by Django 5.0 on 2024-02-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0014_motivationletters_time_participation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationletters',
            name='time',
        ),
        migrations.RemoveField(
            model_name='timeparticipation',
            name='timerestrictions_ptr',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='time',
        ),
        migrations.DeleteModel(
            name='TimeMotivationLetters',
        ),
        migrations.DeleteModel(
            name='TimeRestrictions',
        ),
        migrations.DeleteModel(
            name='TimeParticipation',
        ),
    ]
